<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="48Z0TT3" failures="1" tests="12" name="opencart1" time="66.701" errors="0" timestamp="16 Apr 2024 13:43:40 GMT">
  <testcase classname="login.LoginTests" name="test08AllLoginComponentsAreVisible" time="0.711"/>
  <testcase classname="login.LoginTests" name="test01LoginCustomerSuccessfully" time="1.249"/>
  <testcase classname="login.LoginTests" name="test02ExpectedLoginPageWhenBrowserBackButtonAfterLogout" time="2.395"/>
  <testcase classname="login.LoginTests" name="test03ExpectedWarningMessageWhenLoginCustomerWithInvalidPassword" time="0.894"/>
  <testcase classname="login.LoginTests" name="test04ExpectedWarningMessageWhenLoginCustomerWithInvalidUsername" time="0.922"/>
  <testcase classname="login.LoginTests" name="test05ExpectedWarningMessageWhenLoginCustomerWithEmptyUsername" time="0.978"/>
  <testcase classname="login.LoginTests" name="test06ExpectedWarningMessageWhenLoginCustomerWithEmptyPassword" time="1.028"/>
  <testcase classname="login.LoginTests" name="test07ExpectedWarningMessageWhenLoginCustomerWithInvalidCredentialsMultipleTimes" time="0.602">
    <failure type="java.lang.AssertionError" message="Error in the expected message for wrong login expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]">
      <![CDATA[java.lang.AssertionError: Error in the expected message for wrong login expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.] but found [Warning: No match for E-Mail Address and/or Password.]
	at login.LoginTests.test07ExpectedWarningMessageWhenLoginCustomerWithInvalidCredentialsMultipleTimes(LoginTests.java:121)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- test07ExpectedWarningMessageWhenLoginCustomerWithInvalidCredentialsMultipleTimes -->
  <testcase classname="login.LoginTests" name="test09JustTestingJenkins" time="0.364"/>
  <testcase classname="login.LoginTests" name="test10JustTestingJenkinsAgainPart2" time="0.395"/>
  <testcase classname="login.LoginTests" name="test11JustTestingJenkinsAgainPart2ERESAYESYES" time="0.362"/>
  <testcase classname="login.LoginTests" name="test12JustTestingJenkinsAgainPart2ERESAYESYES" time="0.378"/>
</testsuite> <!-- opencart1 -->
